<html>
    <body style="background: #e9e9e9;">
        <?php
        $id = null;

        if (!empty($this->usuarioFiltrado)) {
            foreach ($this->usuarioFiltrado as $value) {
                $nome = $value['usuarioNome'];
                $login = $value['usuarioLogin'];
                $senha = $value['usuarioSenha'];
                $id = $value['usuarioId'];
            }
        }
        ?>
        <div style="margin: auto; width: 800px;">
            <fieldset style="text-align: center;">
                <legend>
                    Formulario de Usuarios
                </legend>
                <form action="<?php echo $this->url(array('controller' => 'usuario', 'action' => 'save'), null, true); ?>" method="post">

                    <?php if ($id !== null) { ?>
                        <input type="hidden" name="usuarioId" value="<?php echo $id; ?>">
                    <?php } ?>

                    <label>
                        Digite seu nome 
                    </label><br/>
                    <input type="text" name="usuarioNome" value="<?php echo!empty($nome) ? utf8_encode($nome) : ''; ?>"/><br/>
                    <label>
                        Digite seu login
                    </label><br/>
                    <input type="text" name="usuarioLogin" value="<?php echo!empty($login) ? utf8_encode($login) : ''; ?>"/><br/>
                    <label>
                        Digite sua senha
                    </label><br/>
                    <input type="text" name="usuarioSenha" value=""/>
                    <br/>

                    <br/>
                    <input type="submit">
                    <a href="<?php echo $this->url(array('controller' => 'usuario'), null, true); ?>"> Voltar</a>
                </form>
            </fieldset>
        </div> 
    </body>
</html>