<div style="width: 800px; text-align: center; margin: auto;">
        <a href="<?php echo $this->url(array('controller' => 'usuario', 'action' => 'form'),null,true);?>" class="btn btn-info">Novo</a>
    <table class="table table-hover">
        <thead>
            <tr>
                <th>
                    Nome
                </th>
                <th>
                </th>
            </tr>
        </thead>
        <tbody>
            <?php foreach($this->usuarios as $usuario) { ?>
            <tr>
                <td>
                    <?php echo $usuario['usuarioNome'];?>
                </td>
                <td style="text-align: right;">
                    <a href="<?php echo $this->url(array('controller' => 'usuario', 'action' => 'drop', 'id' => $usuario['usuarioId']));?>" class="btn btn-danger"><i></i> Excluir</a>
                    <a href="<?php echo $this->url(array('controller' => 'usuario', 'action' => 'form','id' => $usuario['usuarioId']));?>" class="btn btn-inverse"><i></i> Editar</a>
                </td>
            </tr>
            <?php } ?>
        </tbody>
    </table>
</div>