<html>
    <body style="background: #e9e9e9;">
        <?php
        $statusLivro = array(
            'devolvido', 'emprestado'
        );
        ?>

        <div style="margin: auto; width: 800px;">
            <fieldset style="text-align: center;">
                <legend>
                    Formulario de Emprestimos
                </legend>
                <form action="<?php echo $this->url(array('controller' => 'emprestimo', 'action' => 'save'), null, true); ?>" method="post">

                    <?php if ($this->emprestimosFiltrado['emprestimoAlunoId'] !== null) { ?>
                        <input type="hidden" name="emprestimoId" value="<?php echo $this->emprestimosFiltrado['emprestimoAlunoId']; ?>">
                    <?php } ?>
                    <label>Escolha o aluno</label><br/>
                    <select name="emprestimoAlunoId">
                        <option> Selecione o Aluno </option>
                        <?php foreach ($this->alunosAll as $value) { ?>

                            <option <?php echo $value['alunoId'] == $this->emprestimosFiltrado['emprestimoAlunoId'] ? 'selected' : ''; ?> value="<?php echo!empty($value['alunoId']) ? $value['alunoId'] : ''; ?>">
                                <?php echo utf8_encode($value['alunoNome']); ?>
                            </option>
                        <?php } ?>
                    </select>
                    <br/>
                    <br/>
                    <label>
                        Digite o assunto do Livro
                    </label><br/>
                    <select name="emprestimoLivroId">
                        <option> Selecione o Livro </option>
                        <?php foreach ($this->livrosAll as $value) { ?>
                            <option <?php echo $value['livroId'] == $this->emprestimosFiltrado['emprestimoLivroId'] ? 'selected' : ''; ?> value="<?php echo!empty($value['livroId']) ? $value['livroId'] : ''; ?>">
                                <?php echo utf8_encode($value['livroAssunto']); ?>
                            </option>
                        <?php } ?>
                    </select>
                    <br/>
                    <br/>
                    <label><?php echo utf8_decode('Data de devolução'); ?></label><br/>
                    <input name="emprestimoDevolucao" type="text" value="<?php echo!empty($this->emprestimosFiltrado['emprestimoDevolucao']) ? $this->emprestimosFiltrado['emprestimoDevolucao'] : ''; ?>"><br/>
                    <br/>
                    <label><?php echo utf8_decode('Status do livro'); ?></label><br/>

                    <select name="emprestimoStatus">
                        <option> Selecione o Status </option>
                        <?php foreach ($statusLivro as $value) { ?>
                            <option <?php echo $value == $this->emprestimosFiltrado['emprestimoStatus'] ? 'selected' : ''; ?> value="<?php echo!empty($value) ? $value : ''; ?>">
                                <?php echo utf8_encode($value); ?>
                            </option>
                        <?php } ?>
                    </select>

                    <br/>
                    <br/>
                    <input type="submit">
                    <a href="<?php echo $this->url(array('controller' => 'emprestimo'), null, true); ?>"> Voltar</a>
                </form>
            </fieldset>
        </div> 
    </body>
</html>