<html>
    <head>
        <title>
            Biblioteca
        </title>
    </head>
    <body>
        <div style="margin: auto; width: 1300px; text-align: center;">
            <form action="<?php echo $this->url(array('controller' => 'auth', 'action' => 'login'), null, true); ?>" method="POST" style="padding: 200px;">
                <label>
                    Digite seu login
                </label><br/>
                <input type="text" name="usuarioLogin"/><br/>

                <label><br/>
                    Digite sua senha
                </label>
                <br/>
                <input type="password" name="usuarioSenha"/><br/><br/>
                <input type="submit" value="logar"/>
            </form>
        </div>
    </body>
</html>
