<html>
    <body style="background: #e9e9e9;">
        <?php
        $id = null;

        if (!empty($this->alunoFiltrado)) {
            foreach ($this->alunoFiltrado as $value) {
                $nome = $value['alunoNome'];
                $curso = $value['alunoCurso'];
                $id = $value['alunoId'];
            }
        }
        ?>
        <div style="margin: auto; width: 800px;">
            <fieldset style="text-align: center;">
                <legend>
                    Formulario de Alunos
                </legend>
                <form action="<?php echo $this->url(array('controller' => 'aluno', 'action' => 'save'), null, true); ?>" method="post">

                    <?php if ($id !== null) { ?>
                        <input type="hidden" name="alunoId" value="<?php echo $id; ?>">
                    <?php } ?>

                    <label>
                        Digite seu nome 
                    </label><br/>
                    <input type="text" name="alunoNome" value="<?php echo!empty($nome) ? $nome : ''; ?>"/><br/>
                    <label>
                        Digite seu Curso
                    </label><br/>
                    <input type="text" name="alunoCurso" value="<?php echo!empty($curso) ? $curso : ''; ?>"/><br/>
                    <br/>

                    <br/>
                    <input type="submit">
                    <a href="<?php echo $this->url(array('controller' => 'aluno'), null, true); ?>"> Voltar</a>
                </form>
            </fieldset>
        </div> 
    </body>
</html>
