<!DOCTYPE html>
<html lang="pt-br">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <meta http-equiv = "Content-Type" content = "text/html; charset=UTF-8" />
        <title>Semana de Iniciação Científica</title>
        <link href = "css/style.css"  rel = "stylesheet" />
        <link href = "css/posicionamento.css"  rel = "stylesheet" />
        <link href = "js/bootstrap.multiselect/css/bootstrap-multiselect.css"  rel = "stylesheet"/>
        <link href = "css/galery.css"  rel = "stylesheet" />
        <link rel="stylesheet" type="text/css" href="js/jquery.multiselect/css/multi-select.css"/>
        <link href = "css/ie.css"  rel = "stylesheet" />
        <link href = "css/reset.css"  rel = "stylesheet" />
        <link href = "css/ie-css3.htc"  rel = "stylesheet" />
        <link href="css/bootstrap.css" rel="stylesheet"/>
        <link href = "vendors/shadowbox/shadowbox.css" type = "text/css" rel = "stylesheet" />
        <script src = "vendors/jquery.min.js" type = "text/javascript"></script>
        <script src="vendors/shadowbox/shadowbox.js" type="text/javascript"></script>
        <script src="functions.js" type="text/javascript"></script>
        <script src="functions.js" type="text/javascript"></script>
        <script src="global.js" type="text/javascript"></script>
        <script src="js/bootstrap.multiselect/js/bootstrap-multiselect.js"></script>    
        <script src="js/jquery.multiselect/js/jquery.multi-select.js"></script>    
        <script type="text/javascript">
            Shadowbox.init();
        </script>

        <script type="text/javascript">
            $(document).ready(function () {
                $('#filter_galery a').click(function () {
                    $('#filter_galery a').removeClass('ativo');
                    $(this).addClass('ativo');
                });
            });
        </script>
    </head>
    <body>
        <div id="all">
            <div id="logo">
                <ul id="menu">
                    <li><a href="<?php echo $this->url(array('controller' => 'usuario', 'action' => 'index'),null,true);?>">Cadastrar Usuario</a></li>
                    <li><a href="<?php echo $this->url(array('controller' => 'aluno', 'action' => 'index'),null,true);?>">Cadastrar Aluno</a></li>
                    <li><a href="<?php echo $this->url(array('controller' => 'livro', 'action' => 'index'),null,true);?>">Cadastrar livro</a></li>
                    <li><a href="<?php echo $this->url(array('controller' => 'emprestimo', 'action' => 'index'),null,true);?>">emprestimos</a></li>
                </ul>
            </div>
            <?php echo $this->layout()->content; ?>

            <div class="clear">
            </div>

            <br/>
            <br/>
            <footer id="footer">
                <section id="footer_content">
                    <aside class="left">

                    </aside>
                    <nav id="footer_menu" class="right"></nav>
                </section>
            </footer>
        </div>
    </body>
</html>