<html>
    <body style="background: #e9e9e9;">
        <?php
        $id = null;

        if (!empty($this->livroFiltrado)) {
            foreach ($this->livroFiltrado as $value) {
                $titulo = $value['livroTitulo'];
                $assunto = $value['livroAssunto'];
                $id = $value['livroId'];
            }
        }
        ?>
        <div style="margin: auto; width: 800px;">
            <fieldset style="text-align: center;">
                <legend>
                    Formulario de Livros
                </legend>
                <form action="<?php echo $this->url(array('controller' => 'livro', 'action' => 'save'), null, true); ?>" method="post">

                    <?php if ($id !== null) { ?>
                        <input type="hidden" name="livroId" value="<?php echo $id; ?>">
                    <?php } ?>

                    <label>
                        Digite o Titulo do Livro
                    </label><br/>
                    <input type="text" name="livroTitulo" value="<?php echo!empty($titulo) ? utf8_encode($titulo) : ''; ?>"/><br/>
                    <label>
                        Digite o assunto do Livro
                    </label><br/>
                    <input type="text" name="livroAssunto" value="<?php echo!empty($assunto) ? utf8_encode($assunto) : ''; ?>"/><br/> 
                    <br/>

                    <br/>
                    <input type="submit">
                    <a href="<?php echo $this->url(array('controller' => 'livro'), null, true); ?>"> Voltar</a>
                </form>
            </fieldset>
        </div>
    </body>
</html>
