<div style="width: 800px; text-align: center; margin: auto;">
    <a href="<?php echo $this->url(array('controller' => 'livro', 'action' => 'form'),null,true);?>" class="btn btn-info  ">Novo</a>
    <table class="table table-hover">
        <thead>
            <tr>
                <th>
                    Nome
                </th>
                <th>
                    Assunto
                </th>
                <th>
                </th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($this->livros as $livro) { ?>
                <tr>
                    <td>
                        <?php echo utf8_encode($livro['livroTitulo']); ?>
                    </td>
                    <td>
                        <?php echo utf8_encode($livro['livroAssunto']); ?>
                    </td>
                    <td style="text-align: right;">
                        <a href="<?php echo $this->url(array('controller' => 'livro', 'action' => 'drop', 'id' => $livro['livroId']), null, true); ?>" class="btn btn-danger"><i></i> Excluir</a>
                        <a href="<?php echo $this->url(array('controller' => 'livro', 'action' => 'form', 'id' => $livro['livroId']), null, true); ?>" class="btn btn-inverse"><i></i> Editar</a>
                    </td>
                </tr>
            <?php } ?>
        </tbody>
    </table>
</div>